### ISSUE TITLE
I'd like to support bitbirds in a project I'm launching

### ISSUE THREAD

**Issue by charlesmarino** [nft-fun/generate-bitbirds#1]
Reach out if interested.

**Comment by jainaagam96** [comment]
Hello @charlesmarino ,
i used this creative repo and develop an script where any one can generate a data set for bitbirds and can use this dataset for Machine Learning, Supervised learning Etc.  User need to input the no. of rows that they need in the datasets. The dataset will be in csv format files.

i am generating a pull request if you find it interesting please accept it.
Regards,
Aagam jain
jainaagam96@gmail.com

**Comment by jainaagam96** [comment]
Please accept my merge request if you find it interesting as soon as posible. as it is a part of important assignment as well.

Thanks
